CLASS ltc DEFINITION INHERITING FROM ztc_lac_svc_loc_dto_builder
          FOR TESTING
          DURATION SHORT
          RISK LEVEL HARMLESS
          FINAL.
ENDCLASS.

CLASS ltc IMPLEMENTATION.
ENDCLASS.
