CLASS ltc DEFINITION INHERITING FROM ztc_lac_oauth2_client_builder
          FOR TESTING
          DURATION SHORT
          RISK LEVEL HARMLESS
          FINAL.
ENDCLASS.

CLASS ltc IMPLEMENTATION.
ENDCLASS.
